jfree/jfreechart

src/main/java/org/jfree/chart/renderer/xy/XYStepRenderer.java

When zooming in on a chart our program would suddenly become very slow and ultimately hang. I was able to trace that back to the recently introduced XYStepRenderer's drawLine method, which took very long when drawing lines not in the display area. XYLineAndShapeRenderer hasn't this issue as it avoids drawing lines not in the display area. Adding the same visibility check in XYStepRenderer resolved the issue for me.

Improve XYStepRenderer to only draw visible lines

---

ant/build-fx.xml
ant/build.xml

Ant Build attempts to copy /ChangeLog, /swt/, and other swt files in the /lib/ directory that don't exist in the repo.  Removal of these instructions allows ant to build successfully.

Fixed issues with ant build.

---

src/main/java/org/jfree/chart/date/SerialDate.java

Both `SerialDate#addMonths` and `SerialDate#addYears` adjust a date by an arbitrary integer number of months/years. The only restriction placed on this integer by the javadoc for these methods is that it "can be negative" - i.e., these methods can be used to adjust the date either forwards or backwards in time.
However, some arguments to these functions are non-sensical, and may result in opaque failures. In particular, a negative argument to `SerialDate#addMonths` with sufficiently large magnitude can cause an `ArrayIndexOutOfBoundsException` to be raised by the `SerialDate#lastDayOfMonth` function that is called later in the function, because the intermediate `mm` value that is calculated could be negative (and `lastDayOfMonth` immediately uses that value to access an array, so it must …

Add error handling code to SerialDate#addMonths and SerialDate#addYears

---

src/main/java/org/jfree/chart/plot/XYPlot.java

**Problem**
When using the default constructor of XYPlot the count of datasets, renderer and axis is 1 instead of expected null.
**Solution**
Add dataset, renderer domainaxis and rangeaxis only to map, when not null.

Default Constructor of XYPlot adds null to Maps

---

src/main/java/org/jfree/data/category/SlidingCategoryDataset.java
src/main/java/org/jfree/data/gantt/SlidingGanttCategoryDataset.java
src/test/java/org/jfree/data/gantt/SlidingGanttCategoryDatasetTest.java

In `org/jfree/data/gantt/SlidingGanttCategoryDataset`, there are a number of methods that take a row key and a column key, look up indexes for them, and dispatch to the underlying dataset. In many of these methods, the column key is checked to make sure that it is valid, but the row key is not. 
For example, consider `SlidingGanttCategoryDataset#getValue`. If an invalid column key is passed, the method cleanly throws an `UnknownKeyException` at the place where the error occurred (consistent with the documentation on the method). If an invalid row key is passed, though, the error is propagated to `TaskSeriesCollection#getRowKey` (assuming that the underlying `GanttCategoryDataset` is a `TaskSeriesCollection`). This error is misleading (it's a generic `IndexOutOfBoundsException`) and …

Ensure row keys are valid in sliding category datasets

---

src/main/java/org/jfree/chart/ui/Layer.java
src/main/java/org/jfree/chart/ui/RectangleAnchor.java
src/main/java/org/jfree/chart/util/Rotation.java
src/main/java/org/jfree/chart/util/SortOrder.java
src/main/java/org/jfree/chart/util/TableOrder.java
src/main/java/org/jfree/chart/util/UnitType.java

This seems superflous since `toString()` is generated automatically.

Remove name fields from enum

---

src/main/java/org/jfree/chart/renderer/xy/SamplingXYLineRenderer.java

We had the problem, that the line to the next point started from a wrong y-value. The starting point was not the last processed y-value but it was the last drawn y-value.
For example: 
final XYSeries series = new XYSeries( "Example" );
series.add( 0.5 , 5.0 );
series.add( 1.0 , 5.0 );
series.add( 1.0001 , 2.0 );
series.add( 1.0002 , 10.0 );
series.add( 1.0003 , 1.0 );
series.add( 2.0 , 5.0 );
With this dataset, the line from x=1.0 to x=2.0 started at y=5.0 but we expected that it would start at y=1.0 because it's the last x-value before x=2.0. With the bugfix the line goes from 1.0003/1.0 to 2.0/5.0.

fixed SamplingXYLineRenderer to draw seriesPath from s.closeY instead of from last drawn y

---

src/main/java/org/jfree/chart/plot/RingPlot.java

The previous documentation of RingPlot specified that certain
methods such as setSectionDepth took percentages (0 to 100) but
this is not correct, in fact they take proportions (0 to 1.0).

Correct documentation in RingPlot: proportion vs percent

---

src/main/java/org/jfree/data/DefaultKeyedValues2D.java

DefaultKeyedValues2D#getRowIndex returns the result of Collections.binarySearch directly if the underlying List is being kept in sorted order. The specification for [Collections.binarySearch](https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#binarySearch(java.util.List,%20T)) is unusual: if the element being searched for is not found, a negative index indicating where to insert the value to keep the list in sorted order is returned. The specification on getRowIndex, defined in the KeyedValues2D interface, says:
``` * @return The row index, or {@code -1} if the key is unrecognised```. 
This pull request changes DefaultKeyedValues2D#getRowIndex to respect the specification written on KeyedValues2D#getRowIndex; an alternative option would be to change the spec there to …

Fix incorrect return value in DefaultKeyedValues2D#getRowIndex

---

src/main/java/org/jfree/chart/renderer/xy/XYAreaRenderer.java

If you set SeriesFillPaint with a color that is not a gradient, it will be ignored, and the SeriesPaint will be used instead.

Fix XYAreaRenderer to use SeriesFillPaint when not a Gradient

---

src/test/java/org/jfree/chart/imagemap/ImageMapUtilsTest.java

Hi,
I've analysed your codebase and noticed that `org.jfree.chart.imagemap.ImageMapUtils` is not fully tested. Subsequently, I've written tests for the `GetImageMap` function with the help of [Diffblue](https://www.diffblue.com/) [Cover](https://www.diffblue.com/datasheet).
Hopefully, these tests should help you detect regressions caused by future code changes. If you have any other classes you would like additional unit tests for, please let me know and I'll be happy to contribute additional tests.

Add tests for org.jfree.chart.imagemap.ImageMapUtils

---

src/test/java/org/jfree/data/time/TimeSeriesCollectionTest.java

As suggested in [issue #114](https://github.com/jfree/jfreechart/issues/114), the problem is fixed [here](https://github.com/jfree/jfreechart/commit/f19cea1ef6daccda17b9999264481c5b517861d8#diff-84fcd834bcd20e78a9936d4b82586186L310). This `backport` branch of `v1.5.x` used `git cherry-pick` to allow the test to pass. Tested in GMT-4.

Backport f19cea1ef6daccda17b9999264481c5b517861d8.

---

src/main/java/org/jfree/chart/ChartPanel.java

For some applications, the defaults were inconvenient. For example, sometimes it is better to pan by default because users need it more often than zoom. In my application, I had to alter events with reflection to get the behavior I wanted, which is ugly, to say the least.
Also, switch to `getModifiersEx()` instead of `getModifiers()` because `getModifiers()` is long deprecated.
Compatibility warning: `panMask` is protected, so whatever subclases expected to find old-style modifiers there (getModifiers()) will fail to do so (because it is now in getModifiersEx() language). Perhaps it was a wrong decision to switch to getModifiers(), but doing otherwise would force users to use deprecated constants. Anyway, the only thing possible subclasses could do with `panMask` is to change pan …

Allow to change modifiers for panning and zooming

---

src/main/java/org/jfree/chart/panel/CrosshairOverlay.java
src/main/java/org/jfree/chart/plot/Crosshair.java

The crosshair has a label offset but it's never used in the code, the paint methods in CrosshairOverlay always apply a hard coded offset of 5 pixels. This PR ensures that the offset defined for the crosshair is really used during the painting.

Apply the offset to the crosshair labels

---

src/main/java/org/jfree/chart/panel/CrosshairOverlay.java

The outline of the label attached to an horizontal crosshair is drawn even if the outline is disabled. This PR aligns the code painting the horizontal crosshair with the code for the vertical crosshair which is correct.

Do not draw the disabled outline of horizontal crosshair's labels

---

src/main/java/org/jfree/chart/renderer/xy/ClusteredXYBarRenderer.java

The drawItem method of the renderer did not consider the visibility of
series before drawing the series items. This is inconsistent with other
renderers.
If this was intentional it should be indicated in some way?

Update ClusteredXYBarRenderer to account for visibility of series

---

src/main/java/org/jfree/data/time/Day.java
src/main/java/org/jfree/data/time/Hour.java
src/main/java/org/jfree/data/time/Millisecond.java
src/main/java/org/jfree/data/time/Minute.java
src/main/java/org/jfree/data/time/Month.java
src/main/java/org/jfree/data/time/Quarter.java
src/main/java/org/jfree/data/time/RegularTimePeriod.java
src/main/java/org/jfree/data/time/Second.java
src/main/java/org/jfree/data/time/TimeSeries.java
src/main/java/org/jfree/data/time/TimeSeriesCollection.java
src/main/java/org/jfree/data/time/Week.java
src/main/java/org/jfree/data/time/Year.java
src/test/java/org/jfree/data/time/DayTest.java
src/test/java/org/jfree/data/time/HourTest.java
src/test/java/org/jfree/data/time/MillisecondTest.java
src/test/java/org/jfree/data/time/MinuteTest.java
src/test/java/org/jfree/data/time/MonthTest.java
src/test/java/org/jfree/data/time/QuarterTest.java
src/test/java/org/jfree/data/time/SecondTest.java
src/test/java/org/jfree/data/time/WeekTest.java
src/test/java/org/jfree/data/time/YearTest.java

In JFreeChart 1.5.0, `RegularTimePeriod` subclasses create a new calendar instance every time they need one, which is during every construction, including via `next()` and `previous()` methods. In most setups, this creates a new `GregorianCalendar` instance, which is very heavyweight (at least two arrays of `int` and one array of `boolean`, 17 elements each). For example, when creating and displaying a chart for 86400 seconds (one day's worth), this doubles memory consumption (200–250 MB instead of slightly above 100). The GC simply can't cope fast enough with this.
Since the calendars are only used temporarily for time calculations (“pegging”) and then immediately discarded, it would make sense to use a single global instance. However, since `Calendar` is mutable, it would create …

Allow to set thread-local calendars and calendar prototype for RegularTimePeriod

---

src/main/java/org/jfree/chart/plot/PiePlot.java
src/main/java/org/jfree/data/DefaultKeyedValue.java
src/main/java/org/jfree/data/DefaultKeyedValues.java
src/main/java/org/jfree/data/KeyedValues.java
src/main/java/org/jfree/data/general/DefaultPieDataset.java
src/main/java/org/jfree/data/general/PieDataset.java
src/test/java/org/jfree/chart/plot/PiePlotTest.java

I fixed a bug with PiePlot that I discovered while trying to run the demo applications against JFC1.5.x :-) A class cast exception is thrown upon startup because it was building the dataset with a number as the key, but trying to access the data using a string (or maybe the opposite?).  
So I added generics, but then realized that the KeyedValues classes needed it too in order to compile.  I ran all the JUnit tests, fixed the demo programs and ran them too with success.
I can attach a copy of the exception to this pull request if you'd like!

Added generics to fix bug with PiePlot/PieDataset

---

src/main/java/module-info.java

I've forked jfreechart-fx and made it use jfreechart 2.0, but jfreechart does not export some packages jfreechart-fx needs. So I've added them.
Please see https://github.com/jfree/jfreechart-fx/pull/19

Export org.jfree.chart.api and org.jfree.chart.plot.pie from module

---

src/main/java/org/jfree/data/general/DefaultPieDataset.java

Backport of fix for wrong null check in `DefaultPieDataset(KeyedValues<K> source)` #216, raised in issue #264.

Backport issue #216.

---

src/test/java/org/jfree/data/general/DatasetUtilsTest.java

`DatasetUtilsTest` fails in `testIterateToFindRangeBounds_BoxAndWhiskerXYDataset`; changed `ArrayList<String>` to `ArrayList<Number>`.

Fix failed DatasetUtilsTest

---

src/test/java/org/jfree/chart/block/AbstractBlockTest.java

I fixed a typo in the class Name of AbstractBlockTest {

Typo in the AbstractBlockTest Class

---

pom.xml

This setting eliminates the following warning emitted by Maven in main and test compile phases:
```console
[WARNING] system modules path not set in conjunction with -source 11
```
For running `mvn`, the `source` and `target` properties could also be removed -- but iirc, then IDE(A)s might not detect the required Java version anymore.

Set `javac`'s release option to 11

---

src/main/java/org/jfree/data/gantt/TaskSeriesCollection.java

This check is already present in this file in other method overloads.

Fix potential NPE in TaskSeriesCollection

---

src/main/java/org/jfree/chart/plot/CompassPlot.java
src/test/java/org/jfree/chart/plot/CompassPlotTest.java

In v1.5.x, add check and test for lower array bound to `CompassPlot::setSeriesNeedle`, mentioned in [CVE-2024-23077](https://github.com/advisories/GHSA-jfc7-fvxq-663f) and [CVE-2023-52070](https://github.com/advisories/GHSA-872f-jfmv-qjp2), raised in issue #396.

CVE-2024-23077.

---

src/main/java/org/jfree/chart/renderer/xy/XYBezierRenderer.java
src/test/java/org/jfree/chart/renderer/xy/XYBezierRendererTest.java

Plot charts using Bezier curves.
With Bezier curves you can control how the curve fits (bends) to the points on the graph. This is done with the parameter 'tension'
This solution arises from the problem defined in stackoverflow:
[StackOverflow question](https://stackoverflow.com/questions/70021577/jfreechart-setautorange-when-xysplinerenderer-is-used-as-rendered)
XYBezierRenderer extends XYLineAndShapeRenderer.
XYBezierRendererTest has been also added to branch.

Add XYBezierRenderer to jfreechart

---

src/main/java/org/jfree/chart/axis/SymbolAxis.java

I have a use case where I need to set the symbols only after the Axis is created.
I am creating instances of all elements in the beginning, generating data and then assembling everything towards the end.

Adding setter for symbols in SymbolAxis

---

src/main/java/org/jfree/chart/plot/Crosshair.java
src/main/java/org/jfree/chart/swing/CrosshairOverlay.java

This PR I has add new crosshair label padding that draw over the `CrosshairOverlay`. and adjusted crosshair label position to be within chart dataArea when LabelAnchor is `CENTER`. this changed apply for both `domainCrosshair` and `rangeCrosshair`
`crosshair.setLabelPadding(new RectangleInsets(3, 5, 3, 5));`
Please check this PR I hope this option have in this JFreeChart. or something wrong with this changed please help improve the code changed. Thank you.

Add crosshair label padding and adjusted crosshair label position when LabelAnchor is center

---

src/main/java/org/jfree/chart/encoders/EncoderUtil.java
src/main/java/org/jfree/chart/encoders/ImageEncoderFactory.java
src/test/java/org/jfree/chart/encoders/EncoderUtilTest.java

Add unit tests to utilities to increase code coverage.

Add tests on EncoderUtils to increase overall code coverage

---

README.md
src/main/java/org/jfree/chart/renderer/AbstractRenderer.java

#364 Adding clearSeriesXXX methods for all series settings
